import assert from 'node:assert/strict';
import {baseAV,changeSpeedAV,defMultiplier,mitigation,baseBreak,coefficients,normalizeElement,directDamage,annihilation,quangValue,applyShields,energyGain,canFollow,runCombat} from './combat.mjs';
import {newPiece,pieceStats} from './artifacts.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
close(baseAV(100.4),100);close(changeSpeedAV(80,100,200),40);close(defMultiplier(60,60),.5);close(defMultiplier(60,60,.8,.4),1);close(mitigation([.6,.6]),.1);close(baseBreak(30),845.5);
assert.equal(coefficients[normalizeElement('Hoả Ngục')],2);assert.equal(coefficients.Quang,1);
assert.equal(coefficients['Vật Lý'],1.5);assert.equal(normalizeElement('Hàn Băng'),'Băng');
assert.deepEqual(applyShields(1200,[1000,600]),{hpDamage:200,shields:[0,0]});close(energyGain(10,.192),11.92);
assert.equal(canFollow('A','A'),false);assert.equal(canFollow('B','A'),true);
assert.equal(quangValue({owner:0,recorded:2000},[{atk:500}]),1000);assert.equal(quangValue({owner:0,recorded:2000},[{atk:1200}]),2000);
const c={name:'Veyr',level:60,atk:1000,hp:100000,speed:100,crit:0,critDmg:.5,energyCap:120,aspect:'Vajra',element:'Quang'};
const target={level:60,res:0,toughness:30,maxToughness:30,reductions:[]};
close(directDamage(c,target,{ratio:1}),450);close(directDamage(c,{...target,toughness:0},{ratio:1}),500);
const a={actor:0,av:1,level:60,source:'Basic',ratio:1,flat:0,hits:1,targets:1,target:0,scaling:'atk',toughness:30,efficiency:0,cost:0,refund:1,energy:20,realTurn:true};
const cfg={count:1,level:60,hp:100000,maxToughness:30,toughness:30,weaknesses:['Quang'],speed:100,attack:100,hitEnergy:10,cycles:1,res:0,critMode:'normal',seed:1};
let r=runCombat(cfg,[c],[{...a,annihilate:true}]);assert.ok(r.log.some(x=>x.message.includes('Diệt Kích')));assert.equal(r.enemies[0].toughness,30);
r=runCombat({...cfg,weaknesses:[]},[c],[a]);assert.ok(!r.log.some(x=>x.message.includes('(Break)')));
r=runCombat({...cfg,weaknesses:[]},[c],[{...a,implant:true}]);assert.ok(r.log.some(x=>x.message.includes('(Break)')));
r=runCombat({...cfg,weaknesses:['Băng']},[{...c,element:'Băng'}],[a]);assert.equal(r.enemies[0].toughness,0);assert.ok(r.log.some(x=>x.message.includes('bỏ hành động')));
r=runCombat({...cfg,maxToughness:15,toughness:15,weaknesses:[],cycles:2},[{...c,element:'Vật Lý'}],[a]);assert.ok(r.log.some(x=>x.message.includes('(Break)')));assert.ok(r.log.some(x=>x.message.includes('(DoT)')));
r=runCombat({...cfg,weaknesses:['Băng']},[{...c,element:'Hàn Băng'}],[a]);assert.ok(r.log.find(x=>x.kind==='direct').amount>800);assert.ok(!r.log.some(x=>x.message.includes('bỏ hành động')));
r=runCombat({...cfg,weaknesses:['Phong']},[{...c,element:'Phong'}],[a]);assert.equal(r.enemies[0].toughness,30);
r=runCombat(cfg,[c],[{...a,source:'Skill',cost:4}]);assert.equal(r.enemies[0].hp,cfg.hp);assert.ok(r.log.some(x=>x.message.includes('thiếu Planck')));
r=runCombat(cfg,[c],[{...a,source:'FUA',energy:10,refund:0,realTurn:false}]);assert.ok(r.log.some(x=>x.message.includes('NL 70.00/120')));
r=runCombat(cfg,[c],[{...a,source:'FUA',fuaId:'A',parent:'A'}]);assert.equal(r.enemies[0].hp,cfg.hp);
r=runCombat(cfg,[c],[{...a,source:'Buff',recipient:0,buffType:'damage',buffValue:.2,effectName:'test',duration:2},{...a,av:2,source:'Basic'}]);assert.ok(r.log.some(x=>x.message.includes('540.00 (direct)')));
const p=newPiece(4);p.subs[0].stat='crit';assert.throws(()=>pieceStats(p),/trùng/);
console.log('PASS combat formulas, Break, controls, resources, targeting support, FUA and artifact validation');
