const reportUI={input:null,result:null,saved:[],actor:'all',source:'all',page:0};
const reportFmt=n=>Number.isFinite(n)?n.toLocaleString('vi-VN',{maximumFractionDigits:4}):'—';
function reportTable(labels,rows){const table=rotationNode('table');table.append(rotationTableHead(labels));const body=rotationNode('tbody');for(const values of rows){const tr=rotationNode('tr');for(const value of values){const td=rotationNode('td');if(value instanceof Node)td.append(value);else td.textContent=String(value);tr.append(td);}body.append(tr);}table.append(body);return table;}
function setupReportUI(){
 const panel=rotationNode('section');panel.id='combatReport';panel.className='panel rotation-planner';panel.append(rotationNode('h2','Báo cáo sát thương'),rotationNode('p','Số liệu lấy tại từng hit. Sát thương thực tế được giới hạn bởi HP còn lại của Myrk; phần vượt HP được ghi riêng, kể cả khi cơ chế chuyển tiếp có thể sử dụng nó.'));
 for(const id of ['reportSummary','reportFilters','reportGroups','reportHits','reportDiagnostics']){const n=rotationNode('div');n.id=id;panel.append(n);}document.querySelector('#rotationPlanner').after(panel);
 const compare=rotationNode('section');compare.id='teamComparison';compare.className='panel rotation-planner';compare.append(rotationNode('h2','So sánh đội hình'),rotationNode('p','Lưu riêng 5 Veyr, trang bị, chỉ số và rotation của mỗi phương án. Tất cả đội đã lưu sẽ chạy lại trên cấu hình Myrk, số cycle và seed hiện tại.'));
 const controls=rotationNode('div');controls.className='rotation-controls';const name=rotationNode('input');name.id='teamSnapshotName';name.placeholder='Tên phương án đội hình';name.setAttribute('aria-label','Tên phương án đội hình');controls.append(name,rotationButton('Lưu đội & rotation',saveReportTeam,'saveReportTeam'),rotationButton('So sánh các đội đã lưu',compareReportTeams,'compareReportTeams'));compare.append(controls);
 for(const id of ['teamReportMessage','savedReportTeams','teamReportResults']){const n=rotationNode(id==='teamReportMessage'?'p':'div');n.id=id;compare.append(n);}panel.after(compare);
 try{const saved=JSON.parse(localStorage.getItem('mythborne-teams-v1')||'[]');reportUI.saved=Array.isArray(saved)?saved.filter(s=>typeof s?.name==='string'&&Array.isArray(s.roster)).slice(0,10):[];}catch{teamReportMessage('Không đọc được các đội đã lưu trong trình duyệt này.');}renderReportTeams();
}
function clearCombatReport(message){if(!document.querySelector('#combatReport'))return;reportUI.result=null;for(const id of ['reportGroups','reportHits','reportDiagnostics','teamReportResults'])document.getElementById(id).replaceChildren();document.querySelector('#reportSummary').textContent=message;}
function reportUpdated(input,result){reportUI.input=input;reportUI.result=result;document.querySelector('#teamReportResults').replaceChildren();if(!result.complete){clearCombatReport(result.error);return;}renderCombatReport();}
function renderCombatReport(){
 const {result,input}=reportUI;if(!result?.complete)return;const sum=summarizeReport(result),host=document.querySelector('#reportSummary');host.replaceChildren(rotationNode('h3','Đóng góp của từng Veyr'));
 host.append(reportTable(['Veyr','Sát thương thực tế','Đóng góp','Năng Lượng cuối','Lượt thực tế'],input.roster.map((u,i)=>[u.name,reportFmt(result.totals[u.name]||0),sum.total?((result.totals[u.name]||0)/sum.total*100).toFixed(2)+'%':'0%',reportFmt(result.units[i].currentEnergy),result.units[i].turn])));
 host.append(rotationNode('p',`Tổng ST thực tế: ${reportFmt(sum.total)} · ${result.damageEvents.length} hit · Tổng phần vượt HP của từng hit: ${reportFmt(sum.overkill)} · Planck cuối: ${result.planck}`));
 const filters=document.querySelector('#reportFilters');filters.className='rotation-controls';filters.replaceChildren(rotationSelect('Lọc báo cáo theo Veyr',[['all','Tất cả Veyr'],...input.roster.map((u,i)=>[i,u.name])],reportUI.actor,v=>{reportUI.actor=v;reportUI.page=0;renderCombatReport();}),rotationSelect('Lọc nguồn sát thương',[['all','Tất cả nguồn'],...Object.entries(reportSources)],reportUI.source,v=>{reportUI.source=v;reportUI.page=0;renderCombatReport();}));
 const matches=h=>(reportUI.actor==='all'||h.actor===Number(reportUI.actor))&&(reportUI.source==='all'||(h.category||h.source)===reportUI.source);
 const groups=sum.groups.filter(matches),g=document.querySelector('#reportGroups');g.replaceChildren(rotationNode('h3','Theo kỹ năng và nguồn sát thương'),reportTable(['Veyr','Nguồn','Kỹ năng / hiệu ứng','Số hit','ST thực tế','Vượt HP'],groups.map(v=>[input.roster[v.actor].name,reportSources[v.source]||v.source,v.name,v.hits,reportFmt(v.actual),reportFmt(v.overkill)])));
 const hits=result.damageEvents.filter(matches),pages=Math.max(1,Math.ceil(hits.length/50));reportUI.page=Math.min(reportUI.page,pages-1);const h=document.querySelector('#reportHits');h.replaceChildren(rotationNode('h3','Giải thích từng hit'));
 const nav=rotationNode('div');nav.className='rotation-controls';const prev=rotationButton('Trang trước',()=>{reportUI.page--;renderCombatReport();}),next=rotationButton('Trang sau',()=>{reportUI.page++;renderCombatReport();});prev.disabled=reportUI.page===0;next.disabled=reportUI.page>=pages-1;nav.append(prev,rotationNode('span',`Trang ${reportUI.page+1}/${pages} · ${hits.length} hit`),next);h.append(nav);
 h.append(reportTable(['AV','Veyr / Myrk','Đòn đánh','ST thực tế','Phép tính'],hits.slice(reportUI.page*50,(reportUI.page+1)*50).map(hit=>{
  const d=rotationNode('details');d.append(rotationNode('summary','Xem công thức'));
  d.append(rotationNode('p',`Nguồn đòn: ${reportSources[hit.source]||hit.source} · Nhóm sát thương: ${reportSources[hit.damageSource]||hit.damageSource}${hit.countsAsDK?' · Đồng thời kích hoạt hiệu ứng Diệt Kích':''}`));
  const p=hit.parameters,isStored=hit.factors[0]?.label==='Giá trị đã xác định / ghi nhận',isCarry=hit.factors[0]?.label==='Sát thương dư trước DEF/Kháng';d.append(rotationNode('p',`Chỉ số tại thời điểm: ATK ${reportFmt(hit.stats.atk)} · HP ${reportFmt(hit.stats.hp)} · PT ${reportFmt(hit.stats.def)} · Cấp ${hit.stats.level||60}.`));
  if(!isStored&&!isCarry&&!['Break','Diệt Kích'].includes(hit.formulaType))d.append(rotationNode('p',`Chỉ số tính đòn: ${{atk:'Tấn Công',hp:'HP',def:'Phòng Thủ',speed:'Tốc Độ'}[p.scaling]||p.scaling}; hệ số ${reportFmt(p.ratio*100)}% + ${reportFmt(p.extraRatio*100)}%, cố định ${reportFmt(p.flat)}.`));
  d.append(reportTable(['Thành phần','Hệ số / giá trị'],hit.factors.map(f=>[f.label,reportFmt(f.value)])));
  if(!isStored)d.append(rotationNode('p',`Giảm DEF ${reportFmt(p.defReduction*100)}% · Xuyên Giáp ${reportFmt(p.pen*100)}% · Kháng Myrk ${reportFmt(p.res*100)}% · Xuyên Kháng ${reportFmt(p.resPen*100)}%${p.ignoreDefRes?' · Đòn bỏ qua DEF/Kháng':''}.`));
  d.append(rotationNode('p',`Tích các thành phần: ${reportFmt(hit.formulaValue)}. ST tính được: ${reportFmt(hit.calculated)}. HP trước hit: ${reportFmt(hit.hpBefore)}. ST thực tế: ${reportFmt(hit.actual)}. Phần vượt HP: ${reportFmt(hit.overkill)}.`));
  if(hit.quang)d.append(rotationNode('p',`Quang Tích ghi 20% sát thương hợp lệ: ${reportFmt(hit.quang.recorded)}; giới hạn theo 200% ATK hiện tại của người Phá Vỡ: ${reportFmt(hit.quang.cap)}. Lấy giá trị nhỏ hơn.`));
  const effectText=arr=>arr.map(e=>`${e.name} ×${e.stacks}${e.duration===null?'':` (${e.duration} lượt)`}`).join(' · ')||'Không có';d.append(rotationNode('p','Hiệu ứng đang có trên Veyr: '+effectText(hit.effects)),rotationNode('p','Hiệu ứng đang có trên Myrk: '+effectText(hit.targetEffects)));
  return [hit.av.toFixed(2),`${input.roster[hit.actor].name} → Myrk ${hit.target+1}`,hit.name,reportFmt(hit.actual),d];
 })));
 const diag=document.querySelector('#reportDiagnostics');diag.replaceChildren(rotationNode('h3','Tài nguyên và hành động cần kiểm tra'));
 const counts={};for(const d of sum.diagnostics)counts[d.type]=(counts[d.type]||0)+1;
 const labels={fallback:'Đổi sang BA vì thiếu Planck',planck:'Bỏ đòn vì thiếu Planck',energy:'Tuyệt Kĩ thiếu Năng Lượng',target:'Mục tiêu không hợp lệ',control:'Bị khống chế',hp:'Không đủ HP',expired:'Hiệu ứng hết hạn',energyOverflow:'Năng Lượng tràn',planckOverflow:'Planck tràn'};
 diag.append(rotationNode('p',Object.entries(counts).map(([k,v])=>`${labels[k]||k}: ${v}`).join(' · ')||'Không ghi nhận hành động bị chặn, tài nguyên tràn hoặc hiệu ứng hết hạn.'));
 const details=rotationNode('details');details.append(rotationNode('summary',`Xem ${sum.diagnostics.length} sự kiện`),reportTable(['AV','Sự kiện'],sum.diagnostics.map(d=>[d.av.toFixed(2),d.message])));diag.append(details);
 diag.append(rotationNode('p','Các sự kiện là quan sát trong rotation này. Hiệu ứng hết hạn hoặc tài nguyên tràn không tự động đồng nghĩa đội hình yếu; đối chiếu với đòn đánh và thời điểm kế tiếp.'));
}
function teamReportMessage(message){document.querySelector('#teamReportMessage').textContent=message;}
function persistReportTeams(){try{localStorage.setItem('mythborne-teams-v1',JSON.stringify(reportUI.saved));return true;}catch{teamReportMessage('Không lưu được lâu dài; các đội hiện chỉ được giữ trong phiên này.');return false;}}
function saveReportTeam(){
 if(!reportUI.result?.complete){teamReportMessage('Chạy mô phỏng hợp lệ trước khi lưu đội.');return;}const name=document.querySelector('#teamSnapshotName').value.trim();if(!name){teamReportMessage('Nhập tên phương án đội hình.');return;}if(reportUI.saved.length>=10){teamReportMessage('Đã lưu 10 đội; xóa một bản cũ để lưu thêm.');return;}
 const data={};document.dispatchEvent(new CustomEvent('mythborne-build-snapshot',{detail:data}));if(!data.build){teamReportMessage('Chưa lấy được cấu hình trang bị; thử lại khi bộ chọn tải xong.');return;}
 const saved=teamSnapshot(name,reportUI.input,data.build);saved.seeds=[...document.querySelectorAll('.action-row')].map(row=>Object.fromEntries([...row.querySelectorAll('input,select')].map(e=>[e.className,e.value])));reportUI.saved.push(saved);const persisted=persistReportTeams();renderReportTeams();if(persisted)teamReportMessage('Đã lưu “'+name+'”, gồm trang bị, chỉ số, Vận Mệnh và rotation.');document.querySelector('#teamReportResults').replaceChildren();
}
function renderReportTeams(){const host=document.querySelector('#savedReportTeams');host.replaceChildren();for(const s of reportUI.saved){const line=rotationNode('div');line.className='rotation-controls';line.append(rotationNode('span',s.name+' · '+s.roster.map(u=>u.name).join(' / ')),rotationButton('Nạp đội '+s.name,()=>{
 try{validateTeamSnapshot(s);if(!s.build||!s.seeds)throw Error('Bản lưu chưa có cấu hình để nạp.');rotationUI.busy=true;document.dispatchEvent(new CustomEvent('mythborne-build-restore',{detail:{build:s.build}}));rotationUI.plan=JSON.parse(JSON.stringify(s.rotation||null));document.querySelector('#timelineMode').value=s.dynamic?'dynamic':'manual';document.querySelector('#rotation').replaceChildren();for(const seed of s.seeds)addAction(seed);}catch(e){teamReportMessage(e.message);}finally{rotationUI.busy=false;}simulate();
 }),rotationButton('Xóa đội '+s.name,()=>{reportUI.saved=reportUI.saved.filter(x=>x.id!==s.id);persistReportTeams();renderReportTeams();document.querySelector('#teamReportResults').replaceChildren();}));host.append(line);}}
function compareReportTeams(){
 if(!reportUI.result?.complete){teamReportMessage('Sửa cấu hình hiện tại để mô phỏng được trước khi so sánh.');return;}if(!reportUI.saved.length){teamReportMessage('Lưu ít nhất một phương án đội hình.');return;}const host=document.querySelector('#teamReportResults');host.replaceChildren();const common=reportUI.input.config,rows=[];
 for(const saved of reportUI.saved){try{const r=compareTeamSnapshot(saved,common);rows.push([saved.name,reportFmt(r.summary.total),reportFmt(r.damagePer100AV),r.cleared?`Dọn xong tại AV ${r.result.elapsedAV.toFixed(2)}`:`Còn ${r.result.enemies.filter(e=>e.hp>0).length} Myrk`,saved.roster.map(u=>`${u.name}: ${reportFmt(r.result.totals[u.name]||0)}`).join(' · '),`${r.survivors}/5 sống · ${r.kitCount}/5 kit tự động`,`${r.result.planck} Planck · ${r.result.units.map(u=>`${u.name}: ${reportFmt(u.currentEnergy)} NL / ${u.turn} lượt`).join(' · ')}`,`${r.summary.diagnostics.filter(d=>['planck','energy','control','target','hp'].includes(d.type)).length} đòn bị chặn · ${r.summary.diagnostics.filter(d=>d.type==='fallback').length} lần đổi BA`]);}catch(e){rows.push([saved.name,'Không so sánh',e.message,'—','—','—','—','—']);}}
 host.append(rotationNode('p',`Mỗi Myrk: ${common.hp} HP, ${common.maxToughness} Sức Bền tối đa (${common.toughness} ban đầu), Tốc Độ ${common.speed}. ${common.cycles} cycle = ${150+100*(common.cycles-1)} AV · Seed ${common.seed}. ST/100 AV chia cho cùng toàn bộ thời lượng, kể cả đội dọn xong sớm. Các mục tiêu, Kháng, Điểm Yếu và chế độ Chí Mạng cũng dùng cấu hình hiện tại.`),reportTable(['Đội & rotation','Tổng ST','ST / 100 AV','Kết quả Myrk','ST từng Veyr','Trạng thái đội','Tài nguyên / lượt cuối','Điểm nghẽn'],rows));teamReportMessage('Đã tính lại các đội trên cùng điều kiện. Đổi cấu hình sẽ xóa bảng cũ; trang bị và rotation của từng đội vẫn được giữ trong bản lưu.');
}
