import {normalizeElement} from '../formulas.mjs';
export const dianMuKit={
 minor:{hp:.25,speed:5,energy:.1},
 gate(r){return r.ctx.units.every(t=>['Băng','Lôi'].includes(normalizeElement(t.element)));},
 sync(r,u){if(r.asc(u))for(const t of r.allies()){const shield=t.shieldLayers?.some(x=>x.key==='character-shield:'+u.index+':Lôi Kính'&&x.value>0);if(shield)r.buff(u,t,'Dian Mu A2',{resist:.2});else r.remove(u,t,'Dian Mu A2');}},
 shield(r,u,t,value,duration,a){const layer=r.shieldValue(u,t,value,duration,a,'character-shield:'+u.index+':Lôi Kính');if(layer){layer.initial=value;layer.dianTriggered=false;}return layer;},
 init(r,u){r.state(u).superconduct=dianMuKit.gate(r);if(r.asc(u)){const value=(.18*r.eff(u).hp+320)*.6;for(const t of r.allies())dianMuKit.shield(r,u,t,value,2,{});}},
 resolve(r,u,k){return k==='Basic'?{name:'A Flash Across Closed Eyes',ratio:.7,toughness:30}:k==='Skill'?{name:'Let No Thunder Reach Them',support:true}:{name:'The Sky Lowers Its Brightest Mirror',support:true,energyCost:150};},
 after(r,u,a){if(a.ability==='Basic'){const t=r.ctx.enemies[a.primaryTarget];if(r.debuff(u,t,'Điện Trệ',2,a)){r.buff(u,t,'Điện Trệ',{speed:-8},2,{debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:{...a,buffType:'speed',buffValue:-8},disrupt:true});}}if(a.ability==='Skill'){const value=.18*r.eff(u).hp+320;for(const t of r.allies())dianMuKit.shield(r,u,t,value,3,a);}if(a.ability==='Ult'){const base=.18*r.eff(u).hp+320;for(const t of r.allies()){const key='character-shield:'+u.index+':Lôi Kính',layer=t.shieldLayers.find(x=>x.key===key&&x.value>0);if(layer){layer.value=layer.initial;layer.duration=Math.min(3,layer.duration+1);}else dianMuKit.shield(r,u,t,.7*base,2,a);t.shields=t.shieldLayers.map(x=>x.value);}for(const t of r.enemies()){if(r.debuff(u,t,'Trời Nén',2,a)){const amount=r.vm(u,4)?-.3:-.2;r.buff(u,t,'Trời Nén',{speedPct:amount},2,{debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:{...a,buffType:'speedPct',buffValue:amount},disrupt:true});if(r.vm(u,4))r.delay(t,.15);}}}},
 event(r,u,type,e){if(type==='modify'&&r.state(u).superconduct&&e.unit.side!=='enemy'&&e.unit.element!=='Hàn Băng'&&['Băng','Lôi'].includes(normalizeElement(e.unit.element))){e.action.damageElements=['Băng','Lôi'];e.action.elementName='Siêu Dẫn';const hp=r.eff(u).hp;e.bonus+=Math.min(r.vm(u,1)?.4:.3,hp/100*(r.vm(u,1)?.008:.006));if(r.vm(u,2))e.pen+=.3;if(r.vm(u,6))e.bonus+=hp*.00002;}if(type==='beforeEnemyDamage'&&r.asc(u)&&['Điện Trệ','Trời Nén'].some(k=>r.effect(u,e.enemy,k)))e.amount*=.88;if(type==='enemyAttackEnd'){for(const i of e.recipients||[]){const t=r.ctx.units[i],key='character-shield:'+u.index+':Lôi Kính',layer=t.shieldLayers.find(x=>x.key===key);if(!layer||layer.dianTriggered)continue;layer.dianTriggered=true;const enemy=e.enemy;if(r.debuff(u,enemy,'Điện Trệ',2,e.action))r.buff(u,enemy,'Điện Trệ',{speed:-8},2,{debuff:true});}}}
};
