export const floriaKit={
 minor:{def:.18,hp:.1,speed:4},
 init(r,u){if(r.asc(u))for(const t of r.allies())r.shieldValue(u,t,.08*r.eff(u).def+120,1,{ability:'Passive'},r.shieldKey(u)+':Hoa');},
 bloom(r,u,boost=1,broken=false){const s=r.state(u),bud=s.bud;if(!bud)return;s.bud=null;const bearer=r.ctx.units[bud.target];bearer.shieldLayers=bearer.shieldLayers.filter(l=>l.key!==r.shieldKey(u)+':Nụ');bearer.shields=bearer.shieldLayers.map(l=>l.value);const ratio=(r.vm(u,6)?.55:.35)+(broken&&r.vm(u,2)?.1:0),value=.06*r.eff(u).def+120+ratio*bud.stored*boost;for(const t of r.allies())r.shieldValue(u,t,value,2,{ability:'Talent'},r.shieldKey(u)+':Hoa');if(r.asc(u)&&r.once(u,'Nở Hoa'))r.gain(u,5);r.log(u,'Nở Hoa');},
 plant(r,u,t,a,mult=1){if(!r.alive(t))return;const value=(.18*r.eff(u).def+360)*(r.vm(u,1)?1.15:1)*mult,layer=r.shieldValue(u,t,value,3,a,r.shieldKey(u)+':Nụ');r.state(u).bud={target:t.index,stored:0,initial:layer.initial};},
 sync(r,u){if(r.vm(u,4))r.buff(u,u,'VM4',{def:.24});const bud=r.state(u).bud;if(bud&&!r.ctx.units[bud.target].shieldLayers.some(l=>l.key===r.shieldKey(u)+':Nụ'))floriaKit.bloom(r,u);},
 resolve(r,u,k){return k==='Basic'?{name:'Glasspetal Touch',ratio:.8,toughness:30}:k==='Skill'?{name:'Seed Beneath Stone',support:true,needsRecipient:true}:{name:'Garden Wakes at Once',support:true,energyCost:110};},
 after(r,u,a){if(a.ability==='Skill'){floriaKit.bloom(r,u);floriaKit.plant(r,u,r.ctx.units[a.recipient],a);r.allySkill(u,r.ctx.units[a.recipient],a);}if(a.ability==='Ult'){const bud=r.state(u).bud,t=bud?r.ctx.units[bud.target]:r.allies().sort((a,b)=>a.currentHP/r.eff(a).hp-b.currentHP/r.eff(b).hp||Math.abs(a.index-u.index)-Math.abs(b.index-u.index)||a.index-b.index)[0];floriaKit.bloom(r,u,1.25);floriaKit.plant(r,u,t,a,1.2);}},
 event(r,u,type,e){if(type!=='shieldHit'||e.owner!==u)return;const bud=r.state(u).bud;if(!bud||bud.target!==e.target.index)return;const old=e.layers.find(l=>l.key===r.shieldKey(u)+':Nụ');if(!old||old.value<=0)return;bud.stored=Math.min(bud.initial*((r.asc(u)?1.5:1.2)+(r.vm(u,6)?.3:0)),bud.stored+Math.min(old.value,e.incoming));const layer=e.target.shieldLayers.find(l=>l.key===old.key);if(!layer||layer.value<=0)floriaKit.bloom(r,u,1,true);}
};
