import {normalizeElement} from '../formulas.mjs';
export const heraKit={
 minor:{def:.18,hit:.18,speed:6},
 shielded(r,u,t){return t.shieldLayers.some(l=>l.owner===u.index&&l.value>0);},
 sync(r,u){const n=r.ctx.units.filter(t=>normalizeElement(t.element)==='Thủy').length;r.state(u).water=n;for(const t of r.allies()){if(r.vm(u,1))r.buff(u,t,'VM1',{critDmg:n===1?.1:0});if(r.vm(u,4))r.buff(u,t,'VM4',{crit:heraKit.shielded(r,u,t)?.2:0});}},
 resolve(r,u,k){return k==='Basic'?{name:'A Feather Before the Throne',ratio:.7}:k==='Skill'?{name:'Eyes of the Queen',support:true}:{name:'No Voice Above the Crown',support:true,energyCost:130};},
 after(r,u,a,targets){if(['Skill','Ult'].includes(a.ability)){const skill=a.ability==='Skill';for(const t of r.allies())r.shieldValue(u,t,(skill?.16:.22)*r.eff(u).def+(skill?480:680),2,a);for(const t of r.enemies()){if(skill){r.buff(u,t,'Dưới Ánh Mắt Nữ Vương',{resist:r.asc(u)?-.1:0},2,{debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:a});}else{if(r.debuff(u,t,'Triều Đình Tĩnh Lặng',1,a)){r.buff(u,t,'Triều Đình Tĩnh Lặng',{speed:-10},1,{debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:a,disrupt:true});}if((r.effect(u,t,'Mắt Khổng Tước')?.charges||0)>=3&&r.debuff(u,t,'Giam Thuỷ',1,a)){r.buff(u,t,'Giam Thuỷ',{},1,{type:'control',debuff:true});r.delay(t,.25);r.remove(u,t,'Mắt Khổng Tước');r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:a,disrupt:true,hardDisrupt:true});if(r.vm(u,2)&&r.once(u,'Giam Thuỷ '+t.index))for(const ally of r.allies()){for(const l of ally.shieldLayers)if(l.owner===u.index&&l.value>0)l.value+=.08*r.eff(u).def+180;ally.shields=ally.shieldLayers.map(l=>l.value);}if(r.vm(u,6)&&r.once(u,'Giam Thuỷ AA'))for(const ally of r.allies())if(heraKit.shielded(r,u,ally))r.advance(ally,.12);}}}}
  if(a.source==='FUA')for(const i of targets){const t=r.ctx.enemies[i],b=r.effect(u,t,'Mắt Khổng Tước');if((b?.charges||0)>=3){r.delay(t,.15);b.duration=2;if(r.asc(u))r.gain(u,5);}else if(r.debuff(u,t,'Mắt Khổng Tước',2,a)){r.buff(u,t,'Mắt Khổng Tước',{},2,{charges:(b?.charges||0)+1,debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:a});}}
 },
 observe(r,u,{unit:t,action:a,targets}){if(r.vm(u,1)&&r.state(u).water>=3&&r.attack(a)&&targets.size)for(const [target,value] of Object.entries(a.damageByTarget||{}))r.queue(t,{name:'Hera VM1',source:'Extra',ratio:0,flat:value*.3,trueDamage:true,energy:0,toughness:0,target:Number(target)},a);},
 event(r,u,type,e){if(type==='shieldAttack'&&e.layers.some(l=>l.owner===u.index&&l.value>0)&&r.once(u,'The Bird Never Looks Away'))r.queue(u,{name:'The Bird Never Looks Away',source:'FUA',ratio:.55,target:e.enemy.index},{chain:e.chain,actor:u.index});if(type==='modify'&&normalizeElement(e.unit.element)==='Thủy'){if(r.effect(u,e.target,'Dưới Ánh Mắt Nữ Vương')){e.resPen+=.08;if(r.asc(u)&&heraKit.shielded(r,u,e.unit))e.bonus+=.1;}if(r.effect(u,e.target,'Triều Đình Tĩnh Lặng'))e.resPen+=.1;e.resPen+=(r.effect(u,e.target,'Mắt Khổng Tước')?.charges||0)*.03;if(r.vm(u,6)&&(r.effect(u,e.target,'Triều Đình Tĩnh Lặng')||r.effect(u,e.target,'Giam Thuỷ')))e.resPen+=.12;if(r.vm(u,1)&&r.state(u).water===2)e.bonus+=.2;}}
};
