export const hermesKit={
 requiresCrit:u=>(u.kitFate||0)>=4,minor:{speed:8,critDmg:.2,energy:.04},
 resolve(r,u,k){return k==='Basic'?{name:'Passing Gale',ratio:.7}:k==='Skill'?{name:'Winged Dispatch',support:true,otherRecipient:true,cost:r.state(u).free?0:1}:{name:'The Sky Arrives First',support:true,energyCost:140};},
 after(r,u,a){const s=r.state(u);if(a.ability==='Skill'){s.free=false;const t=r.ctx.units[a.recipient];r.buff(u,t,'Winged Dispatch',{damage:.2,atk:r.asc(u)?.15:0},1);s.waiting??=new Set();s.waiting.add(t.index);if(r.vm(u,6))r.buff(u,t,'Đường Trời',{},1,{scoped:{resPen:.2},consumeNext:true});r.advance(t,1);r.allySkill(u,t,a);}if(a.ability==='Ult'){s.sky=(s.sky||0)+1;s.signals=0;const bonus=r.eff(u).critDmg*.3+.15;for(const t of r.allies())r.buff(u,t,'The Sky Arrives First',{critDmg:bonus,damage:r.effect(u,t,'Winged Dispatch')?.12:0},2);if(r.asc(u))s.free=true;}},
 event(r,u,type,e){const s=r.state(u);if(type==='turnStart'&&s.waiting?.has(e.unit.index)){const t=e.unit;s.waiting.delete(t.index);s.acting??={};s.acting[t.index]=t.turn;s.routes=Math.min(r.vm(u,1)?2:3,(s.routes||0)+1);if(r.asc(u))r.gain(u,5);if(s.routes>=(r.vm(u,1)?2:3)&&r.once(u,'Lộ Trình')){s.routes=0;r.planck(u,1);r.gain(u,8);}}
  if(type==='hit'&&e.crit&&e.amount>0&&r.vm(u,4)&&r.effect(u,e.unit,'The Sky Arrives First')){s.signals=Math.min(3,(s.signals||0)+1);if(s.signals>=3&&r.once(u,'Tín Lộ',s.sky)){s.signals=0;r.gain(u,20);}}
 },
 observe(r,u,{unit:t,action:a,targets}){const s=r.state(u);if(targets.size&&r.attack(a)){if(a.realTurn&&s.acting?.[t.index]===t.turn){delete s.acting[t.index];r.buff(u,u,'No Message Arrives Late',{speedPct:.08},1);}const road=r.effect(u,t,'Đường Trời');if(road){r.remove(u,t,'Đường Trời');r.advance(t,.25);}if(t!==u&&r.vm(u,2))for(const i of targets){const e=r.ctx.enemies[i];if(e.weaknesses.includes('Phong')||e.effects.some(b=>b.type==='weakness'&&b.element==='Phong'))r.queue(u,{name:'Hermes VM2',source:'FUA',target:i,ratio:1,forceCrit:true},a);}}}
};
