export const ishtarKit={
 minor:{crit:.104,critDmg:.12,elementDamage:.1},
 marked(r,u){return r.enemies().filter(t=>r.effect(u,t,'Tinh Môn'));},
 throne(r,u){return r.enemies().find(t=>r.effect(u,t,'Vương Tọa'));},
 setMarks(r,u,targets,primary,a){for(const t of r.enemies()){r.remove(u,t,'Tinh Môn');r.remove(u,t,'Vương Tọa');}for(const t of targets.slice(0,3))r.buff(u,t,'Tinh Môn',{},3,{debuff:true});if(r.alive(primary))r.buff(u,primary,'Vương Tọa',{},3,{debuff:true});},
 path(r,u,from,to,parent,ult=false){const marked=ishtarKit.marked(r,u),order=[from,...marked.filter(t=>t!==from&&t!==to),to].filter((t,i,a)=>t&&a.indexOf(t)===i),base=r.vm(u,1)?.9:.7,ratios={};order.forEach((t,i)=>ratios[t.index]=base+(r.asc(u)?.15*i:0));const reverse=r.vm(u,6)?(r.effect(u,u,'Nữ Vương Giữa Bảy Thành')?1:.5):(r.effect(u,u,'Nữ Vương Giữa Bảy Thành')?(r.vm(u,2)?.7:.5):0);r.queue(u,{name:'A Queen Crosses Every Gate',source:'Extra',damageSource:'Skill',targetIndices:order.map(t=>t.index),targetRatios:ratios,ratio:0,toughness:10,ishtarPath:true},parent);if(reverse)r.queue(u,{name:'A Queen Crosses Every Gate · Return',source:'Extra',damageSource:'Skill',targetIndices:[...order].reverse().map(t=>t.index),targetRatios:Object.fromEntries([...order].reverse().map((t,i)=>[t.index,(base+(r.asc(u)?.15*i:0))*reverse])),ratio:0,toughness:0,ishtarPath:true},parent);},
 init(r,u){if(!r.asc(u))return;const ts=r.enemies().sort((a,b)=>b.maxHP-a.maxHP||Math.abs(a.index-(r.ctx.enemies.length-1)/2)-Math.abs(b.index-(r.ctx.enemies.length-1)/2)).slice(0,3);ishtarKit.setMarks(r,u,ts,ts[0],{});},
 resolve(r,u,k,input){const target=input.target??0;return k==='Basic'?{name:'A Star Above the Lion Gate',ratio:1,toughness:30}:k==='Skill'?{name:'The Lion Changes Its Gate',ratio:.95,primaryRatio:1.7,blast:true,toughness:30,targetToughness:{[target]:60}}:{name:'Seven Walls Fall in One Night',ratio:1.5,primaryRatio:2.6,blast:true,toughness:45,targetToughness:{[target]:90},energyCost:130};},
 before(r,u,a){a.oldThrone=ishtarKit.throne(r,u)?.index;if(a.ability==='Skill'&&r.state(u).shifted){a.pen=(a.pen||0)+.18;r.state(u).shifted=false;}},
 after(r,u,a,targets){const t=r.ctx.enemies[a.primaryTarget];if(a.ability==='Basic'&&r.effect(u,t,'Tinh Môn')){for(const e of r.enemies())r.remove(u,e,'Vương Tọa');r.buff(u,t,'Vương Tọa',{},r.effect(u,t,'Tinh Môn')?.duration||3,{debuff:true});if(r.asc(u))r.state(u).shifted=true;}if(a.ability==='Skill'){const from=r.ctx.enemies[a.oldThrone];if(from&&from!==t&&r.effect(u,from,'Tinh Môn')&&r.effect(u,t,'Tinh Môn'))ishtarKit.path(r,u,from,t,a);ishtarKit.setMarks(r,u,[...targets].map(i=>r.ctx.enemies[i]),t,a);}if(a.ability==='Ult'){ishtarKit.setMarks(r,u,[...targets].map(i=>r.ctx.enemies[i]),t,a);ishtarKit.path(r,u,t,t,a,true);r.buff(u,u,'Nữ Vương Giữa Bảy Thành',{},r.vm(u,2)?3:2);}if(a.ishtarPath&&r.vm(u,4))for(const i of targets)r.buff(u,r.ctx.enemies[i],'Ishtar VM4',{LôiResReduction:.12},2,{debuff:true});}
};
