import {normalizeElement,toughnessScale} from '../formulas.mjs';
export const marekKit={
 minor:{break:.18,speed:8,hp:.12},
 mark(r,u){return r.enemies().find(t=>r.effect(u,t,'Mối Nối Yếu'));},
 apply(r,u,t,duration){for(const e of r.enemies())if(e!==t)r.remove(u,e,'Mối Nối Yếu');r.buff(u,t,'Mối Nối Yếu',{},duration,{debuff:true});},
 init(r,u){if(r.asc(u)){const t=r.enemies().sort((a,b)=>b.maxToughness-a.maxToughness||a.index-b.index)[0];if(t)marekKit.apply(r,u,t,2);}},
 resolve(r,u,k){return k==='Basic'?{name:'Sound the Depth Gauge',ratio:.7,toughness:30}:k==='Skill'?{name:'Set the Failure Line',ratio:1,toughness:60}:{name:'Open Every Floodgate',ratio:1.1,aoe:true,toughness:120,energyCost:130};},
 after(r,u,a,targets){if(a.ability==='Skill')marekKit.apply(r,u,r.ctx.enemies[a.primaryTarget],3);if(a.ability==='Ult')for(const t of r.enemies())r.buff(u,t,'Van Khóa',{},2,{debuff:true});},
 event(r,u,type,e){const mark=e.target&&r.effect(u,e.target,'Mối Nối Yếu');if(type==='beforeDamage'&&mark&&r.attack(e.action)){const a=e.action;a.marekBoost??=new Set();if(!a.marekBoost.has(e.target.index)){a.marekBoost.add(e.target.index);a.targetToughness??={};a.targetToughness[e.target.index]=(a.targetToughness[e.target.index]??a.toughness)+(r.vm(u,1)?15:10);a.marekBefore??={};a.marekBefore[e.target.index]=e.target.toughness;}}if(type==='break'&&mark&&e.action.marekBefore?.[e.target.index]!==undefined){const a=e.action,base=(a.targetToughness?.[e.target.index]??a.toughness)*toughnessScale(normalizeElement(e.unit.element))*(1+(a.efficiency||0)+(r.eff(e.unit).efficiency||0)),overflow=Math.max(0,base-a.marekBefore[e.target.index]),amount=Math.min(r.asc(u)?40:30,.6*overflow),others=r.enemies().filter(t=>t!==e.target).slice(0,r.vm(u,4)?Infinity:2);for(const t of others)r.ctx.reduceToughness(e.unit,t,amount,{...a,marekTransfer:true});if(r.asc(u))r.buff(u,e.unit,'Dội Áp',{break:.24},2);if(r.vm(u,6)&&others.some(t=>t.toughness===0)&&r.once(u,'Marek VM6',a.uid)){r.gain(e.unit,20);r.advance(e.unit,.3);}}if(type==='recover'){const b=r.effect(u,e.enemy,'Van Khóa');if(b){e.enemy.toughness*=r.vm(u,2)?.5:.7;r.remove(u,e.enemy,'Van Khóa');}}if(type==='death'&&e.unit.side==='enemy'&&r.vm(u,1)&&r.effect(u,e.unit,'Mối Nối Yếu')){const t=r.enemies().sort((a,b)=>b.toughness-a.toughness||a.index-b.index)[0];if(t)marekKit.apply(r,u,t,2);}}
};
