import {addDot,dotStacks} from '../dot-system.mjs';
export const nyxKit={
 minor:{atk:.18,hit:.18,speed:5},
 init(r,u){if(r.asc(u))r.buff(u,u,'Nyx A2',{hit:.3});},
 bleed(r,u,t,a){const count=t.dots.filter(d=>d.name!=='Chảy Máu'||d.owner!==u.index).length;if(!count)return;addDot(t,{name:'Chảy Máu',owner:u.index,action:{actor:u.index,source:'DoT',ability:'DoT',effectName:'Chảy Máu',ratio:2,flat:0,scaling:'atk',bonus:0,toughness:0},duration:2,stacks:count,maxStacks:r.vm(u,4)?10:6,independentDurations:true,separateByOwner:true,row:a.row});},
 sync(r,u){if(r.vm(u,6)){const stacks=Math.max(0,...r.enemies().flatMap(t=>t.dots.filter(d=>d.owner===u.index&&d.name==='Chảy Máu').map(dotStacks)));r.buff(u,u,'Nyx VM6',{elementDamage:.1*Math.min(10,stacks)});}},
 resolve(r,u,k){return k==='Basic'?{name:'Ink Bites the Hand',ratio:.7,toughness:30}:k==='Skill'?{name:'Six Lines Across the Page',ratio:1,aoe:true,toughness:60}:{name:'Read the Sentence Aloud',ratio:1.6,aoe:true,toughness:90,energyCost:160};},
 after(r,u,a,targets){if(a.ability==='Skill'){let energy=0;for(const i of targets){const t=r.ctx.enemies[i],has=t.dots.length>0;if(r.debuff(u,t,'Nguyền Rủa',3,a)){r.buff(u,t,'Nguyền Rủa',{defReduction:.25},3,{debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:a});if(r.asc(u)&&has&&energy<15){energy+=5;r.gain(u,5);}}}}if(a.ability==='Ult'){for(const i of targets){const t=r.ctx.enemies[i];if(r.debuff(u,t,'Hành Quyết',2,a)){r.buff(u,t,'Hành Quyết',{resist:-.3},2,{incoming:{vulnerability:r.asc(u)?.2:0},sources:['DoT'],debuff:true});r.ctx.gear.dispatch('debuff',{unit:u,target:t,action:a});for(const el of ['Nham','Hỏa','Phong','Băng','Lôi','Thủy','Ám','Quang'])r.buff(u,t,'Hành Quyết '+el,{},2,{type:'weakness',element:el,debuff:true});}for(const d of [...t.dots].filter(d=>d.name==='Chảy Máu'))r.tick(u,t,d,d.owner===u.index&&r.vm(u,1)?1.3:1,a);}if(r.vm(u,1))r.planck(u,1);}},
 event(r,u,type,e){if(type==='debuff'&&e.action?.source==='DoT'&&e.target&&e.action.effectName!=='Chảy Máu'){const key=(e.action.uid??e.action.row??'x')+':'+e.target.index;if(r.once(u,'Nyx talent '+key,key))nyxKit.bleed(r,u,e.target,e.action);}if(type==='externalDot'){e.action.ignoreDef=true;if(e.unit===u&&e.action.effectName==='Chảy Máu'&&r.vm(u,1))e.action.ratio*=1.3;}if(type==='modify'&&e.action.dot&&r.vm(u,2)){e.action.allowDotCrit=true;e.crit+=.2;e.critDmg+=1;}}
};
