export const skadiKit={
 minor:{crit:.104,critDmg:.16,elementDamage:.1},
 prey(r,u){return r.enemies().find(t=>r.effect(u,t,'Con Mồi Trắng'));},
 setPrey(r,u,t){for(const e of r.enemies())if(e!==t)r.remove(u,e,'Con Mồi Trắng');if(r.alive(t))r.buff(u,t,'Con Mồi Trắng',{},null,{debuff:true});},
 init(r,u){r.state(u).shells=r.asc(u)?3:0;const t=r.enemies().sort((a,b)=>b.maxHP-a.maxHP||a.index-b.index)[0];if(t)skadiKit.setPrey(r,u,t);},
 resolve(r,u,k,input){const s=r.state(u),shells=s.shells||0,enhanced=k==='Skill'&&shells>=6,ratio=enhanced?3+Math.min(12,shells)*.5:k==='Skill'?1.8:k==='Ult'?3.6:.8;return {name:k==='Basic'?'One Shell Across the White Expanse':k==='Skill'?(enhanced?'White Silence at Point-Blank':'No Footprints Within Range'):'The Winter Palace Fires Once',ratio,toughness:k==='Ult'?120:k==='Skill'?60:30,energyCost:k==='Ult'?140:undefined,enhanced,shells,forceCrit:false};},
 before(r,u,a){if(a.enhanced){a.critBonus=(a.critBonus||0)+(r.asc(u)?.02*Math.min(12,a.shells):0);if(r.vm(u,6)){a.resPen=(a.resPen||0)+.03*a.shells;a.critDmgBonus=(a.critDmgBonus||0)+.04*a.shells;}if(r.vm(u,4)){const buffs=new Set(u.effects.filter(e=>e.owner!==u.index&&!e.debuff).map(e=>e.characterKey||e.gearKey||e.name));a.critDmgBonus=(a.critDmgBonus||0)+.08*Math.min(4,buffs.size);}}},
 after(r,u,a,targets){const t=r.ctx.enemies[a.primaryTarget];if(targets.size)skadiKit.setPrey(r,u,t);const s=r.state(u);if(a.enhanced){s.shells=r.vm(u,1)?Math.floor(a.shells/2):0;if(r.vm(u,6))r.queue(u,{name:'White Silence at Point-Blank · Echo',source:'Extra',damageSource:'Skill',ratio:a.ratio*.5,target:t.index,toughness:0,energy:0},a);}if(a.ability==='Ult'){s.shells=Math.min(12,(s.shells||0)+(r.vm(u,2)?6:4));if(r.vm(u,2))r.advance(u,1);else if(r.asc(u)&&s.shells>=6)r.advance(u,.3);}},
 event(r,u,type,e){if(type==='turnStart'&&e.unit===u){let buffs=new Set(u.effects.filter(x=>x.owner!==u.index&&!x.debuff).map(x=>x.characterKey||x.gearKey||x.name)),t=skadiKit.prey(r,u);if(!t){t=r.enemies().sort((a,b)=>b.maxHP-a.maxHP||a.index-b.index)[0];if(t)skadiKit.setPrey(r,u,t);}const debuffs=new Set(t?[...t.effects.filter(x=>x.debuff),...t.dots].map(x=>x.characterKey||x.gearKey||x.name):[]);r.state(u).shells=Math.min(12,(r.state(u).shells||0)+Math.min(6,buffs.size+debuffs.size));}}
};
