import {normalizeElement} from '../formulas.mjs';
export const taranisKit={
 minor:{speed:8,hp:.12,energy:.1},
 gate(r){return r.ctx.units.every(t=>['Băng','Lôi'].includes(normalizeElement(t.element)));},
 sync(r,u){if(r.vm(u,4))for(const t of r.allies())if(['Băng','Lôi'].includes(normalizeElement(t.element)))r.buff(u,t,'Taranis VM4',{critDmg:.4});},
 holder(r,u){return r.allies().find(t=>r.effect(u,t,'Người Giữ Nét'));},
 conductive(r,u){return r.enemies().find(t=>r.effect(u,t,'Sơn Dẫn Điện'));},
 applyCross(r,u,source,a){if(!r.state(u).loop)return;const el=normalizeElement(source.element),key=el==='Lôi'?'Lam Điện':el==='Băng'?'Bạch Dẫn':null;if(!key)return;for(const t of r.allies()){const te=normalizeElement(t.element),valid=key==='Lam Điện'?te==='Băng':te==='Lôi';if(valid)r.buff(u,t,key,key==='Lam Điện'?{critDmg:.24}:{damage:.18},1);const holder=taranisKit.holder(r,u);if(holder===t&&r.vm(u,6))r.buff(u,t,key==='Lam Điện'?'Bạch Dẫn':'Lam Điện',key==='Lam Điện'?{damage:.18}:{critDmg:.24},1);}const h=taranisKit.holder(r,u);if(h&&r.asc(u)&&r.once(u,'Taranis A2')){r.gain(h,6);if(r.vm(u,2))r.advance(h,.15);}},
 init(r,u){r.state(u).loop=taranisKit.gate(r);if(r.state(u).loop&&r.asc(u))for(const t of r.allies()){const el=normalizeElement(t.element);if(el==='Băng')r.buff(u,t,'Lam Điện',{critDmg:.24},1);if(el==='Lôi')r.buff(u,t,'Bạch Dẫn',{damage:.18},1);}},
 resolve(r,u,k){const target=r.enemies().sort((x,y)=>y.maxHP-x.maxHP||x.index-y.index)[0]?.index??0;return k==='Basic'?{name:'Backhand Through Neon',ratio:.7,toughness:30}:k==='Skill'?{name:'Leave Your Mark on the Storm',ratio:1,toughness:60,target,otherRecipient:true,needsRecipient:true}:{name:'The City Answers in Thunder',ratio:1.2,aoe:true,toughness:90,energyCost:150};},
 after(r,u,a,targets){if(a.ability==='Skill'){const ally=r.ctx.units[a.recipient];for(const t of r.allies())if(t!==ally)r.remove(u,t,'Người Giữ Nét');r.buff(u,ally,'Người Giữ Nét',{damage:.22},3);const enemy=r.ctx.enemies[a.primaryTarget??a.target];for(const t of r.enemies())if(t!==enemy)r.remove(u,t,'Sơn Dẫn Điện');r.buff(u,enemy,'Sơn Dẫn Điện',{},3,{debuff:true});r.allySkill(u,ally,a);}if(a.ability==='Basic'&&r.asc(u)&&r.state(u).loop){const t=r.ctx.enemies[a.primaryTarget];for(const e of r.enemies())if(e!==t)r.remove(u,e,'Sơn Dẫn Điện');r.buff(u,t,'Sơn Dẫn Điện',{},2,{debuff:true});}if(a.ability==='Ult')for(const t of r.allies())r.buff(u,t,'Tường Sét',{atk:.18},2,{scoped:{resPen:['Băng','Lôi'].includes(normalizeElement(t.element))?.15:0}});},
 observe(r,u,{unit,action:a,targets}){if(!r.state(u).loop||!targets.size||!r.attack(a))return;taranisKit.applyCross(r,u,unit,a);if(r.vm(u,1)&&a.realTurn){const t=r.enemies().sort((x,y)=>y.hp-x.hp||x.index-y.index)[0],value=Object.values(a.damageByTarget||{}).reduce((n,v)=>n+v,0);if(t&&value)r.fixed(u,t,.3*value,a,'Taranis VM1','Talent');}},
 event(r,u,type,e){if(type==='modify'&&r.effect(u,e.target,'Sơn Dẫn Điện')&&['Băng','Lôi'].includes(normalizeElement(e.unit.element)))e.vulnerability+=.12;}
};
